version: "2.1"
services:
  php-cli:
    image: exozet/php-fpm:7.1.10-sudo
    user: www-data
    entrypoint: bash
    volumes:
      - ./:/usr/src/app:cached
      - ./.docker/cache/composer:/composer/cache/
    env_file:
      - ./.docker/common.env
      - ./.env
    depends_on:
      - nginx
      - mysql
      - memcached
  php-fpm:
    image: exozet/php-fpm:7.1.10-sudo
    depends_on:
      - mysql
      - memcached
    env_file:
      - ./.docker/common.env
      - ./.env
    volumes:
      - ./:/usr/src/app:cached
    ports:
      - "9000"
      # to make it locally available to the host, use: "9000:9000"
  mysql-cli:
    image: mysql:5.6.35
    env_file:
      - ./.docker/common.env
      - ./.env
    entrypoint: mysql -hmysql -pcoreuser -uthisisnotsecure exoacademy-core
    depends_on:
      - mysql
  mysql:
      image: mysql:5.6.35
      env_file:
        - ./.docker/common.env
        - ./.env
      volumes:
        - ./.docker/data/mysql:/var/lib/mysql
        - ./.docker/mysql/mysql.cnf:/etc/mysql/conf.d/docker.cnf
      ports:
        - "3306:3306"
        # to make it not locally available to the host, use: "3306"
  nginx:
    image: nginx:1.13.5-alpine
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/usr/src/app:cached
      - ./.docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/xoz.one.crt:/etc/nginx/conf.d/xoz.one.crt
      - ./.docker/nginx/xoz.one.key:/etc/nginx/conf.d/xoz.one.key
  memcached:
    image: memcached:1.5.2-alpine
    ports:
      - "11211"
      # to make it locally available to the host, use: "11211:11211" (localport:11211)
